---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash
      bash -n *.sh
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      account_id: ${ACCOUNT_ID}
      api_key: ${API_KEY}
      kubernetes_cluster_id: ${CLUSTER_ID}
    script: |
      #!/bin/bash
      echo "Create Guestbook"
      IP_ADDR=$(bx cs workers $KUBERNETES_CLUSTER_NAME | grep normal | awk '{ print $2 }')
      if [ -z $IP_ADDR ]; then
        echo "$KUBERNETES_CLUSTER_NAME not created or workers not ready"
        exit 1
      fi

      echo -e "Configuring vars"
      exp=$(bx cs cluster-config $KUBERNETES_CLUSTER_NAME | grep export)
      if [ $? -ne 0 ]; then
        echo "Cluster $KUBERNETES_CLUSTER_NAME not created or not ready."
        exit 1
      fi
      eval "$exp"

      echo -e "Downloading guestbook yml"
      curl --silent "https://raw.githubusercontent.com/kubernetes/kubernetes/master/examples/guestbook/all-in-one/guestbook-all-in-one.yaml" > guestbook.yml

      #Find the line that has the comment about the load balancer and add the nodeport def after this
      let NU=$(awk '/^  # type: LoadBalancer/{ print NR; exit }' guestbook.yml)+3
      NU=$NU\i
      sed -i "$NU\ \ type: NodePort" guestbook.yml #For OSX: brew install gnu-sed; replace sed references with gsed

      echo -e "Deleting previous version of guestbook if it exists"
      kubectl delete --ignore-not-found=true   -f guestbook.yml

      echo -e "Creating pods"
      kubectl create -f guestbook.yml

      PORT=$(kubectl get services | grep frontend | sed 's/.*:\([0-9]*\).*/\1/g')

      echo ""
      echo "View the guestbook at http://$IP_ADDR:$PORT"
